# Generated by Django 4.2.4 on 2023-08-13 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_pedido_producto'),
        ('producto', '0002_producto_venta_masiva_remove_producto_categoria_and_more'),
        ('carrito', '0002_alter_carrito_productos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='producto_venta_masiva',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.categoria'),
        ),
        migrations.AddField(
            model_name='producto_venta_masiva',
            name='sub_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.sub_categoria'),
        ),
    ]
