# Generated by Django 4.2.4 on 2023-08-13 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseño_interior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagene1', models.ImageField(upload_to='interiores')),
                ('imagene2', models.ImageField(upload_to='interiores')),
                ('imagene3', models.ImageField(upload_to='interiores')),
                ('imagene4', models.ImageField(upload_to='interiores')),
                ('imagene5', models.ImageField(upload_to='interiores')),
                ('imagene6', models.ImageField(upload_to='interiores')),
                ('imagene7', models.ImageField(upload_to='interiores')),
                ('imagene8', models.ImageField(upload_to='interiores')),
                ('imagene9', models.ImageField(upload_to='interiores')),
                ('imagene10', models.ImageField(upload_to='interiores')),
                ('descripcion', models.TextField()),
                ('materiales', models.TextField()),
                ('dimensiones', models.CharField(max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.categoria')),
            ],
        ),
    ]
